
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/grandlies
    username: postgres
    password: mussa
    driverClassName: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
